openapi: 3.0.3
info:
  title: ComponentHub API
  description: API cho cửa hàng bán linh kiện điện tử (ComponentHub)
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/health:
    get:
      summary: Health check
      tags: [System]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required: [ok]
  /api/products:
    get:
      summary: List products
      tags: [Products]
      responses:
        '200':
            description: A list of products
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      required: [id, name, price]
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: T-Shirt
        price:
          type: number
          example: 199000
